name: ddnuvem
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+14

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_sign_in: ^6.2.1
  firebase_auth: ^5.1.0
  flutter_svg: ^2.0.10+1
  sign_in_button: ^3.2.0
  package_info_plus: ^8.0.0
  cloud_firestore: ^5.0.1
  provider: ^6.1.2
  firebase_core: ^3.1.0
  shared_preferences: ^2.2.3
  device_info_plus: ^10.1.0
  firebase_storage: ^12.0.1
  carousel_slider: ^4.2.1
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  firebase_app_check: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"
  rename: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/direto_da_nuvem_icon.png
    - assets/DiretoDaNuvem-JustLogo.svg

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/direto_da_nuvem_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/direto_da_nuvem_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"